# Generated by Django 4.0.4 on 2022-12-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_order_address_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
